services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=slls_legal_clinic
      - LANG=en_US.utf8
      - LC_ALL=en_US.utf8
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - slls-network
    restart: unless-stopped
    command: postgres -c 'max_connections=100'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  slls-network:
    driver: bridge

volumes:
  postgres-data: