services:
  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    environment:
      - REACT_APP_API_URL=http://localhost:5555/api
      - PUBLIC_URL=http://localhost:3333
      - WDS_SOCKET_PORT=0
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - ./src/frontend:/app
      - ./src/frontend/public:/app/public
      - /app/node_modules
      - /app/build
      - eslint-cache:/app/node_modules/.cache
    networks:
      - slls-network
    restart: unless-stopped

  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - "5555:5555"
    environment:
      - PORT=5555
      - NODE_ENV=development
      - SEED_DATABASE=true
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=slls_legal_clinic
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - JWT_SECRET=your-secret-key-here
      - JWT_EXPIRY=24h
      - CORS_ORIGIN=http://localhost:3333
    volumes:
      - ./src/backend:/app
      - /app/node_modules
      - ./src/backend/uploads:/app/uploads
    networks:
      - slls-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5555/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  slls-network:
    driver: bridge

volumes:
  eslint-cache:
